server:
  port: 8899

spring:
  application:
    name: config-server-local
  profiles:
    # 使用本机配置文件
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/,classpath:/order-service,classpath:/user
  security:
    basic:
      enabled: true
    # 设置配置中心访问密码
    user:
      name: user01
      password: pwd12356
      
## 如需实现配置中心更改配置后，自动推送到各个客户端，依赖 Spring Cloud Bus 消息中间件可以实现。
## <artifactId>spring-cloud-starter-bus-amqp</artifactId>
