server:
  port: 8762

spring:
  application:
    name: service.order-service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # 多个eureka server
      #defaultZone: http://slave1:8761/eureka/,http://slave2:8761/eureka/
