eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service.order-service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: client-ribbon
    api-b:
      path: /api-b/**
      serviceId: service.order-service-feign