server:
  port: 8762

spring:
  application:
    name: service.order-service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 不加以下配置将无法访问 http://localhost:8762/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"